## Project 6: Matrix Methods - Hill Cipher Codes

Caleb Taber

PHYS 280-WS1

3/6/2023

### Abstract

In this project, I have used the Hill substitution cipher to code and then decode the word "matrix." This is done by using various matrix operations, along with  The message is able to be decoded almost every time, as there is a very small possibility that the key matrix is not computed correctly. Due to constraints on the key matrix, computation time can be slow, as there are a limited number of combinations of matrices that will work.

### Description

This project is a continuation of a project that I completed in MATH 280 Linear Algebra. In this project, I have implemented the Hill Cipher in Python. The code takes a hard-coded message, in this case the word "matrix," converts it to a cipher, and converts it back to the original message. This process was completed by using multiple matrix operations, such as matrix multiplication, and computing determinants and inverses. I used the following sources.

https://www.geeksforgeeks.org/hill-cipher/

https://www.geeksforgeeks.org/how-to-create-a-matrix-of-random-integers-in-python/

https://www.nku.edu/~christensen/1402%20Hill%20cipher%20part%20II.pdf

### Algorithm and Discussion

The Hill Cipher is a type of substitution cipher named after mathematician Lester Hill. It works by taking a message, in this case the word "matrix" and assigns each letter the number of its index in the alphabet from 0 - 25. The numbers are then put in 3x1 column matrices. So, the word "matrix" becomes [12 0 19] [17 8 23].

After converting the message into numbers, a key matrix needs to be created in order to create the coded message. The key matrix is a 3x3 matrix of numbers ranging from 0 - 25 or 1 - 26. In order for the matrix to properly work, the determinant must be able to be equal to any odd number from 1 - 25 modulo 26. This is because the inverse of the matrix is used to decode the cipher.

After finding the key matrix, the matrices containing the alphabet indexes are then multiplied by the key matrix. The product matrix then needs to be taken with modulo 26 in order to produce numbers that fit within the range of the alphabet. Once the numbers are converted to their respective letters, the cipher is produced.

In order to decode the message, the product matrix from before is then multiplied the inverse of the key matrix. The same modulo 26 operation is applied, revealing the same matrices from the original message. Lastly, the numbers are then converted back to their respective letters, giving the original message.

### Implementation and Code

In [1]:
# importing necessary libraries
import numpy as np

In [2]:
# initializing message and making it all lowercase for later calculations
message = "matrix"
message = message.lower()

# initializing empty list to store ascii values
message_list = []

# converting string message to ascii values
for i in message:
    message_list.append(ord(i))

# converts ascii to alphabet index
message_list = np.subtract(message_list, 97)

# converting list to matrix
message_matrix = []
length = len(message_list)
while length > 0:
    message_matrix.append(message_list[:3])
    message_list = message_list[3:]
    length = len(message_list)

# reshaping matrix to column vectors
message_matrix[0] = message_matrix[0].reshape(3,1)
message_matrix[1] = message_matrix[1].reshape(3,1)

print(f"Original message: {message}")
print("Message as alphabet index:")
print(message_matrix[0])
print(message_matrix[1])

Original message: matrix
Message as alphabet index:
[[12]
 [ 0]
 [19]]
[[17]
 [ 8]
 [23]]


In [3]:
# create 3x3 key matrix with random integers from 0 to 25
key_matrix = np.random.randint(0, 25, size=(3, 3))

while(np.linalg.det(key_matrix) != 1%26):
        key_matrix = np.random.randint(0, 25, size=(3, 3))

print("Randomized 3x3 key matrix:")
print(key_matrix)
print("Determinant of key matrix:")
print(np.linalg.det(key_matrix))

Randomized 3x3 key matrix:
[[ 9  4 17]
 [16  8  1]
 [14  7  1]]
Determinant of key matrix:
1.0


In [4]:
# create raw cipher by multiplying key matrix and message matrix
pre_cipher = np.matmul(key_matrix, message_matrix)

# create final cipher by taking modulo 26
cipher_num = np.mod(pre_cipher, 26)

print("Coded message as numerical matrix:")
print(cipher_num)

Coded message as numerical matrix:
[[[15]
  [ 3]
  [ 5]]

 [[ 4]
  [21]
  [ 5]]]


In [5]:
# convert ascii values to char
cipher_dummy = cipher_num.flatten()

cipher_dummy = cipher_dummy.astype(int)

cipher_dummy = np.add(cipher_dummy, 97)

cipher = []

for i in cipher_dummy:
    cipher.append(chr(i))

cipher_pretty = ''.join(cipher)

print(f"Coded message: {cipher_pretty}")

Coded message: pdfevf


In [6]:
# find inverse of key matrix to decode cipher
inverse_key_matrix = np.linalg.inv(key_matrix)

pre_decode = np.matmul(inverse_key_matrix, cipher_num)

decode_num = np.mod(pre_decode, 26)

decode_dummy = np.add(decode_num, 97)

print("Decoded message as alphabet index matrix")
print(decode_num)

Decoded message as alphabet index matrix
[[[12.]
  [ 0.]
  [19.]]

 [[17.]
  [ 8.]
  [23.]]]


In [7]:
# convert decoded ascii to char
decode_dummy = decode_num.flatten()

decode_dummy = decode_dummy.astype(int)

decode_dummy = np.add(decode_dummy, 97)

decoded = []

for i in decode_dummy:
    decoded.append(chr(i))

decoded = ''.join(decoded)

print(f"Decoded message: {decoded}")

Decoded message: matrix


### Results

In [8]:
print(f"Orignial message: {message}")
print(f"Coded message: {cipher_pretty}")
print(f"Decoded message: {decoded}")

Orignial message: matrix
Coded message: pdfevf
Decoded message: matrix


The above cell shows that the original message "matrix" was converted into a cipher. Due to the key matrix being randomized, the cipher will change with every execution. This makes the cipher stronger.

### Conclusion

In this project, I used the Hill substitution cipher to code and then decode the word "matrix." Due to the matrix operations have a small chance of not being exact, there's a very small chance that the message can not be decoded. One way to make it better would be to include all of the odd numbers that are used during the creation of the key matrix. This may also cause the computation time to be faster as there is a larger search space for the key matrix to be created.

<a style='text-decoration:none;line-height:16px;display:flex;color:#5B5B62;padding:10px;justify-content:end;' href='https://deepnote.com?utm_source=created-in-deepnote-cell&projectId=2fd7e31b-262a-40c9-9149-32c7d5c47109' target="_blank">
 </img>
Created in <span style='font-weight:600;margin-left:4px;'>Deepnote</span></a>